import { neon } from "@neondatabase/serverless";
const url = process.env.DATABASE_URL;
if (!url) throw new Error("DATABASE_URL is required");
const sql = neon(url);
await sql`CREATE TABLE IF NOT EXISTS "user" (id text PRIMARY KEY, name text NOT NULL, email text NOT NULL UNIQUE, email_verified boolean NOT NULL DEFAULT false, image text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());`;
await sql`CREATE TABLE IF NOT EXISTS "session" (id text PRIMARY KEY, expires_at timestamptz NOT NULL, token text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), ip_address text, user_agent text, user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE);`;
await sql`CREATE TABLE IF NOT EXISTS "account" (id text PRIMARY KEY, account_id text NOT NULL, provider_id text NOT NULL, user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE, access_token text, refresh_token text, id_token text, access_token_expires_at timestamptz, refresh_token_expires_at timestamptz, scope text, password text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());`;
await sql`CREATE TABLE IF NOT EXISTS "verification" (id text PRIMARY KEY, identifier text NOT NULL, value text NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());`;await sql`CREATE TABLE IF NOT EXISTS products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text NOT NULL UNIQUE, category text NOT NULL DEFAULT 'massage', description text NOT NULL DEFAULT 'Home service massage in Canggu, Bali.', duration_minutes integer NOT NULL, price_idr integer NOT NULL, is_active boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());`;
await sql`CREATE TABLE IF NOT EXISTS site_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key text NOT NULL UNIQUE, value text NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());`;
const rows = [
  ["Balinese Massage","balinese-60",60,300000,"massage"],["Balinese Massage","balinese-90",90,450000,"massage"],["Traditional Massage","traditional-60",60,300000,"massage"],["Traditional Massage","traditional-90",90,450000,"massage"],["Swedish Massage","swedish-60",60,300000,"massage"],["Swedish Massage","swedish-90",90,450000,"massage"],["Lomi-Lomi Massage","lomi-60",60,300000,"massage"],["Lomi-Lomi Massage","lomi-90",90,450000,"massage"],["Foot Massage","foot-60",60,250000,"massage"],["Foot Massage","foot-90",90,350000,"massage"],["Scrub + Massage","scrub-60",60,350000,"massage"],["Scrub + Massage","scrub-90",90,500000,"massage"],["Face Acupressure + Massage","face-acupressure-60",60,350000,"massage"],["Face Acupressure + Massage","face-acupressure-90",90,500000,"massage"],["Deep Tissue","deep-tissue-60",60,350000,"massage"],["Deep Tissue","deep-tissue-90",90,500000,"massage"],["Shiatsu","shiatsu-60",60,350000,"massage"],["Shiatsu","shiatsu-90",90,500000,"massage"],["Hot Stone","hot-stone-60",60,350000,"massage"],["Hot Stone","hot-stone-90",90,500000,"massage"],["Thai Massage","thai-60",60,350000,"massage"],["Thai Massage","thai-90",90,500000,"massage"],["Lymphatic","lymphatic-60",60,500000,"massage"],["Lymphatic","lymphatic-90",90,750000,"massage"],["Pregnant Massage","pregnant-60",60,300000,"massage"],["Pregnant Massage","pregnant-90",90,500000,"massage"],["Massage + Scraping","scraping-60",60,325000,"massage"],["Massage + Scraping","scraping-90",90,475000,"massage"],["Facial","facial",60,250000,"facial"],["Face Massage","face-massage",60,200000,"facial"],["Paket 1: Balinese Massage + Scrub + Facial","package-1",120,500000,"package"],["Paket 2: Balinese Massage + Scrub + Pedi Men","package-2",120,450000,"package"]
];
for (const [name, slug, duration, price, category] of rows) await sql`INSERT INTO products (name, slug, category, description, duration_minutes, price_idr, is_active, sort_order) VALUES (${name}, ${slug}, ${category}, ${`${name} home service massage in Canggu, Bali.`}, ${duration}, ${price}, true, 0) ON CONFLICT (slug) DO UPDATE SET name=excluded.name, category=excluded.category, duration_minutes=excluded.duration_minutes, price_idr=excluded.price_idr, updated_at=now();`;
const settings = { spaName:"Massage Bali", address:"Canggu, Bali", whatsapp:"082326348577", serviceMode:"Home service massage only", heroTitle:"Relax your body. Refresh your mind.", heroSubtitle:"Professional massage treatments delivered to your home in Canggu." };
for (const [key, value] of Object.entries(settings)) await sql`INSERT INTO site_settings (key, value) VALUES (${key}, ${value}) ON CONFLICT (key) DO UPDATE SET value=excluded.value, updated_at=now();`;
const result = await sql`SELECT count(*)::int AS products FROM products`;
console.log(JSON.stringify({ seeded: true, products: result[0].products }));

