"use client";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { authClient } from "@/lib/auth/client";
import { useState } from "react";
import { useForm } from "@tanstack/react-form";
import type { Product, SiteSettings } from "@/lib/data/catalog";
import { productSchema, settingsSchema } from "@/lib/validation/schemas";

type Props = { initialProducts: Product[]; initialSettings: SiteSettings; databaseConfigured: boolean; userEmail: string };
const money = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value);

export function DashboardClient({ initialProducts, initialSettings, databaseConfigured, userEmail }: Props) {
  const [products, setProducts] = useState(initialProducts); const [settings, setSettings] = useState(initialSettings); const [notice, setNotice] = useState("");
  const productForm = useForm({ defaultValues: { name: "", slug: "", category: "massage", description: "Home service massage in Canggu, Bali.", durationMinutes: 60, priceIdr: 300000, isActive: true, sortOrder: products.length }, onSubmit: async ({ value }) => { const parsed = productSchema.safeParse(value); if (!parsed.success) { setNotice(parsed.error.issues[0]?.message ?? "Invalid product"); return; } const response = await fetch("/api/admin/products", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(parsed.data) }); const result = await response.json(); if (!response.ok) { setNotice(result.error ?? "Could not save product"); return; } setProducts((current) => [...current, result.data]); setNotice("Product saved."); productForm.reset(); } });
  const settingsForm = useForm({ defaultValues: settings, onSubmit: async ({ value }) => { const parsed = settingsSchema.safeParse(value); if (!parsed.success) { setNotice(parsed.error.issues[0]?.message ?? "Invalid settings"); return; } const response = await fetch("/api/admin/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(parsed.data) }); const result = await response.json(); if (!response.ok) { setNotice(result.error ?? "Could not save settings"); return; } setSettings(result.data); setNotice("Site settings saved."); } });
  return <main className="dashboard"><header className="dashboard-header"><div><p className="eyebrow">Massage Bali / Admin</p><h1>Content dashboard</h1><p>Manage your home-service menu, prices, and homepage identity.</p></div><Link href="/" className="dashboard-link">View website ↗</Link></header>
    <section className="dashboard-status"><span className="dashboard-user">Signed in as <strong>{userEmail}</strong></span><span className={databaseConfigured ? "status-good" : "status-warn"}>{databaseConfigured ? "NeonDB connected" : "Database unavailable"}</span><Button type="button" variant="outline" onClick={async () => { await authClient.signOut(); window.location.href = "/dashboard/login"; }}>Sign out</Button></section>
    {notice && <p className="dashboard-notice" role="status">{notice}</p>}
    <div className="dashboard-layout"><section className="dashboard-panel"><div className="panel-heading"><div><p className="eyebrow">Pricelist & products</p><h2>Massage menu</h2></div><span>{products.length} items</span></div><div className="product-list">{products.map((product) => <div className="product-row" key={product.id}><div><strong>{product.name}</strong><small>{product.category} · {product.durationMinutes} minutes</small></div><b>{money(product.priceIdr)}</b></div>)}</div><form className="dashboard-form" onSubmit={(event) => { event.preventDefault(); event.stopPropagation(); productForm.handleSubmit(); }}><h3>Add product</h3><div className="form-grid"><productForm.Field name="name">{(field) => <label>Name<Input value={field.state.value} onChange={(event) => field.handleChange(event.target.value)} /></label>}</productForm.Field><productForm.Field name="slug">{(field) => <label>Slug<Input value={field.state.value} onChange={(event) => field.handleChange(event.target.value)} /></label>}</productForm.Field><productForm.Field name="durationMinutes">{(field) => <label>Duration (min)<Input type="number" value={field.state.value} onChange={(event) => field.handleChange(Number(event.target.value))} /></label>}</productForm.Field><productForm.Field name="priceIdr">{(field) => <label>Price (IDR)<Input type="number" value={field.state.value} onChange={(event) => field.handleChange(Number(event.target.value))} /></label>}</productForm.Field></div><productForm.Field name="description">{(field) => <label>Description<Textarea value={field.state.value} onChange={(event) => field.handleChange(event.target.value)} /></label>}</productForm.Field><Button type="submit" className="dashboard-button">Save product</Button></form></section>
      <section className="dashboard-panel"><div className="panel-heading"><div><p className="eyebrow">Homepage content</p><h2>Business settings</h2></div></div><form className="dashboard-form" onSubmit={(event) => { event.preventDefault(); event.stopPropagation(); settingsForm.handleSubmit(); }}><settingsForm.Field name="spaName">{(field) => <label>Spa name<Input value={field.state.value} onChange={(event) => field.handleChange(event.target.value)} /></label>}</settingsForm.Field><settingsForm.Field name="address">{(field) => <label>Address<Input value={field.state.value} onChange={(event) => field.handleChange(event.target.value)} /></label>}</settingsForm.Field><settingsForm.Field name="whatsapp">{(field) => <label>WhatsApp number<Input value={field.state.value} onChange={(event) => field.handleChange(event.target.value)} /></label>}</settingsForm.Field><settingsForm.Field name="serviceMode">{(field) => <label>Service mode<Input value={field.state.value} onChange={(event) => field.handleChange(event.target.value)} /></label>}</settingsForm.Field><settingsForm.Field name="heroTitle">{(field) => <label>Hero title<Input value={field.state.value} onChange={(event) => field.handleChange(event.target.value)} /></label>}</settingsForm.Field><settingsForm.Field name="heroSubtitle">{(field) => <label>Hero subtitle<Textarea value={field.state.value} onChange={(event) => field.handleChange(event.target.value)} /></label>}</settingsForm.Field><Button type="submit" className="dashboard-button">Save homepage settings</Button></form></section></div>
  </main>;
}




